### ISSUE TITLE
Unable to migrate (No module named 'nepali-datetime-field')

### ISSUE THREAD

**Issue by Aananda-giri** [dxillar/django-nepali-datetime-field#1]
Traceback (most recent call last):
  File "project/manage.py", line 22, in <module>
    main()
  File "project/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File ".../lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File ".../lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File ".../lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".../lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File ".../lib/python3.9/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nepali-datetime-field'

**Comment by amitgaru** [comment]
Thank you for finding this bug.

Actually it was a typo in the README doc. Change `nepali-datetime-field` to `nepali_datetime_field` in the INSTALLED_APPS list. 

Fixed that in README too.
